export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const FETCH_PRODUCTS =  "FETCH_PRODUCTS";
export const ADD_TO_CART =  "ADD_TO_CART";
export const REMOVE_FROM_CART =  "REMOVE_FROM_CART";
export const ADJUST_QTY =  "ADJUST_QTY";
export const LOAD_CURRENT_ITEM =  "LOAD_CURRENT_ITEM";
export const FETCH_PRODUCTS_CATEGORY =  "FETCH_PRODUCT_CATEGORY";
export const USER_AUTHENTICATION =  "USER_AUTHENTICATION";