const express =require('express')
const app = express();
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const routesUrls = require('./routes/routers')
const authUrl = require('./routes/auth')
const cors =require('cors')
// const product = require('./modules/searchProduct')

dotenv.config()
mongoose.connect(process.env.DATABASE_ACCESS, ()=>console.log("DataBase Connected"))
app.use(express.json())
app.use(cors())
app.use('/app', routesUrls)
app.use("/auth",authUrl)
app.listen(4000, ()=> console.log("Hello welcome to server"))
app.get("")